AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
